import test from 'node:test';
import assert from 'node:assert/strict';

import { renderShowLogWebviewHtml } from '../src/showLogWebview';
import { renderShowLogWebviewStyles } from '../src/showLog/webviewStyles';

test('composes the Show Log shell with its dedicated style module', () => {
  const styles = renderShowLogWebviewStyles();
  const html = renderShowLogWebviewHtml();

  assert.ok(styles.length > 20_000);
  assert.equal(html.includes(`<style>${styles}</style>`), true);
  assert.equal(html.match(/<style>/g)?.length, 1);
});

test('renders a table-like show log webview shell with graph column and inline commit details support', () => {
  const html = renderShowLogWebviewHtml();

  assert.match(html, /<title>Show Log<\/title>/);
  assert.match(html, /class="table-header"/);
  assert.match(html, /class="summary-count" id="summaryCount"/);
  assert.match(html, /class="filter-input" id="filterInput"/);
  assert.match(html, /placeholder="Filter commits"/);
  assert.match(html, /class="filter-clear" id="filterClear"/);
  assert.match(html, /class="status-card' \+ \(state\.errorMessage \? ' error' : ''\) \+ '" role="status"/);
  assert.match(html, /state\.searchNotice/);
  assert.match(html, /class="commit-tooltip" id="commitTooltip" role="tooltip" hidden/);
  assert.match(html, /graph-header-label">Graph<\/span>/);
  assert.match(html, /Show All Branches/);
  assert.match(html, /id="showAllBranchesToggle"/);
  assert.match(html, /id="graphResizer"/);
  assert.match(html, /class="commit-row"/);
  assert.match(html, /data-selected="/);
  assert.match(html, /class="graph-cell"/);
  assert.match(html, /class="commit-files-graph"/);
  assert.match(html, /class="commit-files-list"/);
  assert.match(html, /class="commit-file-search-control"/);
  assert.match(html, /class="commit-file-search-input"/);
  assert.match(html, /placeholder="Filter files\.\.\."/);
  assert.match(html, /data-commit-file-filter="/);
  assert.match(html, /class="commit-file-search-clear"/);
  assert.match(html, /data-commit-file-filter-clear="/);
  assert.match(html, /\.commit-file-search-row \{\s*display: flex;\s*justify-content: flex-end;/);
  assert.match(html, /\.graph-continuation-row \{\s*--show-log-continuation-height: 24px;\s*display: flex;\s*flex: 0 0 var\(--show-log-continuation-height\);/);
  assert.match(html, /\.graph-continuation-row\.status \{\s*--show-log-continuation-height: 34px;/);
  assert.match(html, /\.graph-continuation-row\.search \{\s*--show-log-continuation-height: 36px;/);
  assert.match(html, /\.graph-continuation-row \.commit-files-graph \.graph-svg \{\s*height: var\(--show-log-continuation-height\);\s*min-height: var\(--show-log-continuation-height\);/);
  assert.match(html, /\.commit-files-list \{[\s\S]*?padding: 0 0 0 12px;/);
  assert.doesNotMatch(html, /\.commit-files-list \{[\s\S]*?padding: 0 0 5px 12px;/);
  assert.match(html, /--show-log-ref-base-branch: #19d60f;/);
  assert.match(html, /--show-log-ref-base-head: #d62828;/);
  assert.match(html, /--show-log-ref-base-tag: #f7f300;/);
  assert.match(html, /--show-log-ref-base-remote: #f6d8a8;/);
  assert.match(html, /--show-log-ref-branch: color-mix\(in srgb, var\(--show-log-ref-base-branch\) 88%, white 12%\);/);
  assert.match(html, /--show-log-ref-head: color-mix\(in srgb, var\(--show-log-ref-base-head\) 92%, white 8%\);/);
  assert.match(html, /--show-log-ref-tag: color-mix\(in srgb, var\(--show-log-ref-base-tag\) 90%, white 10%\);/);
  assert.match(html, /--show-log-ref-remote: color-mix\(in srgb, var\(--show-log-ref-base-remote\) 88%, white 12%\);/);
  assert.doesNotMatch(html, /\.ref-badge::after/);
  assert.match(html, /\.ref-badge\[data-ref-kind="head"\]/);
  assert.match(html, /\.ref-badge\[data-ref-kind="branch"\]/);
  assert.match(html, /\.ref-badge\[data-ref-kind="remote"\]/);
  assert.match(html, /\.ref-badge\[data-ref-kind="tag"\]/);
  assert.match(html, /\.subject-meta \{\s*display: flex;[\s\S]*?overflow: hidden;[\s\S]*?flex-wrap: nowrap;/);
  assert.match(html, /\+ \(commit\.refs\.length > 0\s*\? '      <div class="subject-meta">'/);
  assert.doesNotMatch(html, /class="stats"/);
  assert.doesNotMatch(html, /\n\s*\.stats \{/);
  assert.match(html, /\.refs \{\s*display: flex;[\s\S]*?flex: 1 1 auto;[\s\S]*?overflow: hidden;[\s\S]*?flex-wrap: nowrap;/);
  assert.match(html, /\.ref-badge \{[\s\S]*?flex: 0 1 auto;[\s\S]*?min-width: 0;/);
  assert.match(html, /\.ref-badge-icon \{[\s\S]*?width: 11px;[\s\S]*?stroke: currentColor;/);
  assert.match(html, /\.ref-badge-label \{[\s\S]*?text-overflow: ellipsis;/);
  assert.match(html, /function renderRefBadge\(ref\)/);
  assert.match(html, /function renderShowLogRefBadgeIcon\(kind\)/);
  assert.match(html, /data-ref-kind="' \+ escapeHtml\(ref\.kind\)/);
  assert.match(html, /class="ref-badge-label">'\s*\+\s*escapeHtml\(ref\.label\)/);
  assert.match(html, /case 'branch':[\s\S]*?<circle cx="4\.5" cy="3" r="1\.5"><\/circle>/);
  assert.match(html, /case 'branch':[\s\S]*?<circle cx="4\.5" cy="13" r="1\.5"><\/circle>/);
  assert.match(html, /case 'branch':[\s\S]*?<circle cx="11\.5" cy="5\.5" r="1\.5"><\/circle>/);
  assert.match(html, /case 'branch':[\s\S]*?<path d="M4\.5 4\.5v7M4\.5 10h2\.3a4\.7 4\.7 0 0 0 4\.7-3"><\/path>/);
  assert.match(html, /function renderTopology\(topology, isMerge, isFirstVisible, height\)/);
  assert.match(html, /const GRAPH_MAIN_COMPACT_HEIGHT = 26;/);
  assert.match(html, /const GRAPH_MAIN_HEIGHT = 34;/);
  assert.match(html, /const GRAPH_MAIN_META_HEIGHT = 42;/);
  assert.match(html, /\.commit-row \{[\s\S]*?min-height: var\(--show-log-main-graph-height, 30px\);/);
  assert.match(
    html,
    /\.commit-row:not\(\[data-expanded="true"\]\) \{ grid-template-rows: var\(--show-log-main-graph-height, 30px\) 0; \}/
  );
  assert.match(html, /\.graph-stack \{[\s\S]*?min-height: var\(--show-log-main-graph-height, 30px\);/);
  assert.match(html, /\.graph-svg \{[\s\S]*?min-height: var\(--show-log-main-graph-height, 30px\);/);
  assert.match(html, /function getMainGraphHeight\(commit\)/);
  assert.match(html, /if \(!hasCommitReferences\(commit\)\) \{\s*return GRAPH_MAIN_COMPACT_HEIGHT;\s*\}/);
  assert.match(html, /return commit\.expanded \? GRAPH_MAIN_META_HEIGHT : GRAPH_MAIN_HEIGHT;/);
  assert.match(html, /function hasCommitReferences\(commit\)/);
  assert.match(html, /return !!\(commit\.refs && commit\.refs\.length > 0\);/);
  assert.match(html, /const mainGraphHeightStyle = ' style="--show-log-main-graph-height: ' \+ mainGraphHeight \+ 'px;"';/);
  assert.match(html, /data-expanded="' \+ \(commit\.expanded \? 'true' : 'false'\) \+ '"' \+ mainGraphHeightStyle \+ '>'/);
  assert.match(html, /function renderContinuationTopology\(topology\)/);
  assert.match(html, /const searchContinuation = '<div class="graph-continuation-row search">/);
  assert.match(html, /function getVisibleCommitFileChanges\(commit\)/);
  assert.match(html, /function renderCommitFileSearch\(commitHash, filterText\)/);
  assert.match(html, /function setCommitFileFilter\(commitHash, value\)/);
  assert.match(html, /function restorePendingCommitFileFilterFocus\(\)/);
  assert.match(html, /data-merge="' \+ \(commit\.isMerge \? 'true' : 'false'\)/);
  assert.match(html, /renderCommit\(commit, index\)/);
  assert.doesNotMatch(html, /class="commit-hash"/);
  assert.match(html, /class="commit-subject">' \+ escapeHtml\(commit\.subject\)/);
  assert.match(html, /class="commit-tooltip-hash">' \+ escapeHtml\(commit\.shortHash\)/);
  assert.match(html, /formatWebviewShortDate\(commit\.date\)/);
  assert.match(html, /renderTopology\(commit\.topology, commit\.isMerge, index === 0, mainGraphHeight\)/);
  assert.match(html, /const centerY = \(height \/ 2\) - 2;/);
  assert.match(html, /const laneTopY = isFirstVisible && lane === topology\.nodeLane \? centerY : topY;/);
  assert.match(html, /class="graph-node-marker/);
  assert.match(html, /isFirstVisible \? ' graph-node-outgoing' : ''/);
  assert.match(html, /--show-log-node-color:/);
  assert.match(html, /\.graph-node-marker \{[\s\S]*?top: 50%;[\s\S]*?width: 7px; height: 7px;[\s\S]*?border-radius: 50%;/);
  assert.match(html, /\.graph-node-outgoing, \.graph-node-merge \{ width: 11px; height: 11px;[\s\S]*?background: var\(--vscode-sideBar-background\); \}/);
  assert.match(html, /\.commit-row:hover \.graph-node-marker:not\(\.graph-node-outgoing, \.graph-node-merge\) \{ box-shadow: 0 0 0 2px var\(--show-log-node-color\); \}/);
  assert.match(html, /\.commit-row:hover \.graph-node-outgoing \{ background: var\(--show-log-node-color\); \}/);
  assert.match(html, /class="graph-node-marker graph-node-merge"/);
  assert.match(html, /\.graph-node-merge \{ display: grid; place-items: center; \}/);
  assert.match(html, /\.graph-node-merge::after \{[\s\S]*?width: 5px; height: 5px;[\s\S]*?--vscode-charts-yellow/);
  assert.match(html, /\.commit-row:hover \.graph-node-merge::after \{ position: absolute; inset: -1px; width: auto; height: auto; \}/);
  assert.match(html, /\.commit-tooltip \{/);
  assert.match(html, /var\(--vscode-editorHoverWidget-background/);
  assert.match(html, /function renderCommitTooltip\(commit\)/);
  assert.match(html, /const stats = renderTooltipStats\(commit\.stats\);/);
  assert.match(html, /\+ stats\s*\+ '<div class="commit-tooltip-footer">'/);
  assert.match(html, /max-width: var\(--show-log-ref-max-width, 180px\);/);
  assert.match(html, /white-space: var\(--show-log-ref-white-space, nowrap\); overflow-wrap: var\(--show-log-ref-overflow-wrap, normal\);/);
  assert.match(html, /\.commit-tooltip-refs \{[\s\S]*?--show-log-ref-max-width: 100%; --show-log-ref-white-space: normal; --show-log-ref-overflow-wrap: anywhere;/);
  assert.match(html, /formatWebviewTooltipDate\(commit\.date, 'unknown date'\)/);
  assert.match(html, /function formatWebviewTooltipDate\(value, fallbackText\)/);
  assert.match(html, /new Intl\.DateTimeFormat\('en-US', options\)\.format\(date\)/);
  assert.match(html, /function parseCoAuthors\(message\)/);
  assert.match(html, /function showCommitTooltip\(commitHash, event\)/);
  assert.match(html, /function positionCommitTooltip\(clientX, clientY\)/);
  assert.match(html, /function hideCommitTooltip\(\)/);
  assert.match(html, /function scheduleShowCommitTooltip\(commitHash, event\)/);
  assert.match(html, /function cancelCommitTooltipShow\(\)/);
  assert.match(html, /function scheduleHideCommitTooltip\(\)/);
  assert.match(html, /scheduleShowCommitTooltip\(commitHash, event\);/);
  assert.match(html, /const TOOLTIP_SHOW_DELAY_MS = 500;/);
  assert.match(html, /\}, TOOLTIP_SHOW_DELAY_MS\);/);
  assert.match(html, /content\.addEventListener\('contextmenu', \(event\) => \{\s*hideCommitTooltip\(\);/s);
  assert.match(html, /function cancelCommitTooltipHide\(\)/);
  assert.match(html, /pointer-events: auto;/);
  assert.match(html, /renderCopyHashIconButton\('commit-tooltip-action commit-tooltip-action-icon', 'data-tooltip-action', 'copyCommitHash', commit\.hash\)/);
  assert.match(html, /\.commit-tooltip-hash \{[\s\S]*?color: var\(--vscode-textLink-foreground, var\(--vscode-focusBorder\)\);/s);
  assert.match(html, /\.commit-tooltip-action-icon \{[\s\S]*?width: 22px;[\s\S]*?min-width: 22px;/s);
  assert.match(html, /data-tooltip-action="openCommitOnRemote"/);
  assert.match(html, /Copy Hash/);
  assert.match(html, /Open on Remote/);
  assert.match(html, /content\.addEventListener\('mousemove'/);
  assert.match(html, /content\.addEventListener\('mouseleave'/);
  assert.match(html, /commitTooltip\?\.addEventListener\('mouseenter'/);
  assert.match(html, /commitTooltip\?\.addEventListener\('mouseleave'/);
  assert.match(html, /commitTooltip\?\.addEventListener\('click'/);
  assert.match(html, /type: 'copyCommitHash', commitHash/);
  assert.match(html, /type: 'openCommitOnRemote', commitHash/);
  assert.match(html, /target\.closest\('\[data-change-id\]'\)/);
  assert.match(html, /commitTooltip\.innerHTML = renderCommitTooltip\(commit\);/);
  assert.match(html, /\.commit-row:not\(\[data-expanded="true"\]\) \.graph-main \{\s*flex: 1 1 auto;\s*\}/);
  assert.match(html, /const LANE_COLORS = \[/);
  assert.match(html, /const GRAPH_LANE_SPACING = 10;/);
  assert.match(html, /const GRAPH_LEFT_INSET = 8;/);
  assert.match(html, /const GRAPH_RIGHT_PADDING = 6;/);
  assert.match(html, /const width = getGraphContentWidth\(topology\.laneCount, laneSpacing\);/);
  assert.match(html, /function getGraphContentWidth\(laneCount, laneSpacing\)/);
  assert.match(html, /<svg class="graph-svg" width="/);
  assert.match(html, /style="width: ' \+ width \+ 'px;"/);
  assert.match(html, /preserveAspectRatio="none"/);
  assert.match(html, /function applyGraphColumnWidth\(width\)/);
  assert.match(html, /selectedCommitHashes = normalizeSelectedCommitHashes/);
  assert.match(html, /data-compare-base="/);
  assert.match(html, /data-compare-target="/);
  assert.match(html, /const canCompareSelection = selectedCommitHashes\.length === 2;/);
  assert.match(html, /data-compare-base="' \+ \(canCompareSelection && selectedCommitHashes\[0\] === commit\.hash \? 'true' : 'false'\)/);
  assert.match(html, /\.commit-entry\[data-selected="true"\]/);
  assert.match(html, /--show-log-row-hover: color-mix\(\s*in srgb,\s*var\(--vscode-list-hoverBackground, var\(--vscode-editorHoverWidget-background\)\) 86%,\s*var\(--vscode-list-inactiveSelectionBackground, transparent\)\s*\);/s);
  assert.match(html, /--show-log-row-hover-accent: color-mix\(in srgb, var\(--vscode-focusBorder, #3794ff\) 44%, transparent\);/);
  assert.match(html, /--show-log-menu-item-hover: color-mix\(in srgb, var\(--vscode-focusBorder, #3794ff\) 12%, transparent\);/);
  assert.match(html, /--show-log-selection-color: var\(--vscode-charts-blue, #3794ff\);/);
  assert.doesNotMatch(html, /--show-log-selection-color: var\(--vscode-charts-green, #89d185\);/);
  assert.match(html, /\.commit-row:hover \{\s*background:\s*linear-gradient\(\s*90deg,\s*var\(--show-log-row-hover-accent\) 0 3px,\s*transparent 3px 100%\s*\),\s*var\(--show-log-row-hover\);\s*box-shadow: inset 0 0 0 1px var\(--show-log-row-hover-outline\);/s);
  assert.match(html, /\.commit-row\[data-expanded="true"\]:hover \{/);
  assert.match(html, /\.commit-entry\[data-selected="true"\] \.commit-row \{/);
  assert.match(html, /\.commit-entry\[data-selected="true"\] \.commit-row:hover \{/);
  assert.match(html, /\.context-menu-item \{[\s\S]*?border-radius: 7px;[\s\S]*?font-size: 12px;/);
  assert.match(html, /\.context-menu-item:hover,[\s\S]*?background: var\(--show-log-menu-item-hover\);/);
  assert.match(html, /class="context-menu-item"/);
  assert.doesNotMatch(html, /context-menu-button/);
  assert.match(html, /\.commit-entry\[data-compare-base="true"\] \.subject-cell::after/);
  assert.doesNotMatch(html, /\.commit-entry\[data-compare-target="true"\] \.subject-cell::after/);
  assert.match(html, /content: 'Base';/);
  assert.doesNotMatch(html, /content: 'Compare';/);
  assert.match(html, /text-transform: uppercase;/);
  assert.match(html, /function persistUiState\(\)/);
  assert.match(html, /function normalizeSelectedCommitHashes\(value\)/);
  assert.match(html, /\.slice\(-1000\);/);
  assert.match(html, /function syncSelectedCommitHashes\(commits\)/);
  assert.match(html, /function selectCommit\(commitHash, append\)/);
  assert.match(html, /selectedCommitHashes = \[commitHash\];/);
  assert.match(html, /selectedCommitHashes\.includes\(commitHash\)/);
  assert.match(html, /function clearSelectedCommitHashes\(\)/);
  assert.match(html, /selectedCommitHashes = \[\];\s*persistUiState\(\);\s*return true;/s);
  assert.match(html, /function getCompareSelectionForCommit\(commitHash\)/);
  assert.match(html, /if \(selectedCommitHashes\.length !== 2 \|\| !selectedCommitHashes\.includes\(commitHash\)\)/);
  assert.match(html, /function getCherryPickCommitHashes\(commitHash\)/);
  assert.match(html, /vscode\.setState\(/);
  assert.match(html, /if \(event\.ctrlKey && event\.button === 0\)/);
  assert.match(html, /selectCommit\(commitHash, true\);\s*closeContextMenu\(\);\s*render\(\);\s*return;/s);
  assert.match(html, /closeContextMenu\(\);\s*if \(event\.button === 0 && clearSelectedCommitHashes\(\)\) \{\s*render\(\);\s*\}\s*vscode\.postMessage\(\{ type: 'toggleCommit', commitHash \}\);/s);
  assert.doesNotMatch(html, /selectCommit\(commitHash, false\);\s*closeContextMenu\(\);\s*render\(\);\s*vscode\.postMessage\(\{ type: 'toggleCommit', commitHash \}\);/s);
  assert.match(html, /document\.addEventListener\('pointerdown'/);
  assert.match(html, /type: 'toggleShowAllBranches', value: target\.checked/);
  assert.match(html, /function scheduleFilterUpdate\(value\)/);
  assert.match(html, /const sourceToken = getCurrentSourceToken\(\);/);
  assert.match(html, /type: 'setFilterText', value, sourceToken/);
  assert.match(html, /function clearPendingFilterUpdate\(\)/);
  assert.match(html, /function getCurrentSourceToken\(\)/);
  assert.match(html, /if \(previousSourceToken !== getCurrentSourceToken\(\)\) \{\s*clearPendingFilterUpdate\(\);/s);
  assert.match(html, /filterInput\?\.addEventListener\('input'/);
  assert.match(html, /filterClear\?\.addEventListener\('click'/);
  assert.match(html, /content\.addEventListener\('input'/);
  assert.match(html, /target\.matches\('\[data-commit-file-filter\]'\)/);
  assert.match(html, /content\.addEventListener\('click'/);
  assert.match(html, /data-commit-file-filter-clear/);
  assert.match(html, /class="commit-files"/);
  assert.match(html, /No files match the active filter\./);
  assert.match(html, /target\.closest\('\.commit-file-search-control'\)/);
  assert.match(html, /cursor: pointer;/);
  assert.match(html, /user-select: none;/);
  assert.match(html, /content\.addEventListener\('mousedown'/);
  assert.match(html, /content\.addEventListener\('auxclick'/);
  assert.match(html, /content\.addEventListener\('dblclick'/);
  assert.match(html, /target instanceof HTMLElement && target\.closest\('\[data-change-id\]'\)/);
  assert.match(html, /Double-click to compare\. Press Shift\+F10 or Enter for actions\./);
  assert.match(html, /type: 'openFile',\s*commitHash: fileRow\.getAttribute\('data-commit-hash'\)/s);
  assert.match(html, /id="loadMoreSentinel"/);
  assert.match(html, /IntersectionObserver/);
  assert.match(html, /type: 'loadMore'/);
  assert.match(html, /function applyAppendPatch\(patch\)/);
  assert.match(html, /patch\.sourceToken !== currentState\.sourceToken/);
  assert.match(html, /currentCommits\.length !== patch\.previousCommitCount/);
  assert.match(html, /commits: currentCommits\.concat\(patch\.commits \|\| \[\]\)/);
  assert.match(html, /function syncShowLogChrome\(state\)/);
  assert.match(html, /syncShowLogChrome\(currentState\);/);
  assert.match(html, /showAllBranchesToggle\.disabled = !!state\.loading \|\| !!state\.loadingMore;/);
  assert.match(html, /commitList\.insertAdjacentHTML\('beforeend', appendedMarkup\);/);
  assert.match(html, /function syncLoadMoreBlock\(state\)/);
  assert.match(html, /function renderCommitEntry\(commit, index\)/);
  assert.match(html, /event\.data && event\.data\.type === 'append'/);
  assert.match(html, /vscode\.postMessage\(\{ type: 'ready' \}\);/);
  assert.match(html, /Open Commit Details/);
  assert.match(html, /data-menu-action="checkoutCommit">Checkout to this<\/button>/);
  assert.match(html, /data-menu-action="createTagFromCommit">Create Tag<\/button>/);
  assert.match(html, /Reset to this/);
  assert.match(html, /data-menu-action="compareCommitWithWorktree">Compare with Worktree<\/button>/);
  assert.match(html, /data-menu-action="resetToCommit">Reset to this<\/button>/);
  assert.match(html, /function renderCopyReferenceNameMenu\(commit\)/);
  assert.match(html, /data-menu-action="copyReferenceName"/);
  assert.match(html, /data-ref-name="/);
  assert.match(html, /data-menu-action="copyCommitHash">Copy Hash<\/button>/);
  assert.match(html, /Copy Ref Name/);
  assert.doesNotMatch(html, /Copy Reference Name/);
  assert.match(html, /type: 'copyCommitHash', commitHash: state\.commitHash/);
  assert.match(html, /type: 'copyReferenceName', commitHash: state\.commitHash, refName/);
  assert.match(html, /data-menu-action="compareCommits">Compare<\/button>'\s*\+\s*'<button class="context-menu-item" type="button" data-menu-action="cherryPickCommits">Cherry Pick<\/button>'\s*\+\s*copyReferenceNameMenu/s);
  assert.doesNotMatch(html, /data-menu-action="compareCommits">Compare<\/button>'\s*\+\s*'<button class="context-menu-item" type="button" data-menu-action="cherryPickCommits">Cherry Pick<\/button>'\s*\+\s*'<button class="context-menu-item" type="button" data-menu-action="copyCommitHash">Copy Hash<\/button>'/s);
  assert.match(html, /data-menu-action="cherryPickCommits">Cherry Pick<\/button>'\s*\+\s*'<button class="context-menu-item" type="button" data-menu-action="resetToCommit">Reset to this<\/button>'\s*\+\s*'<button class="context-menu-item" type="button" data-menu-action="copyCommitHash">Copy Hash<\/button>'\s*\+\s*copyReferenceNameMenu/s);
  assert.match(html, /function isMultiSelectedContext\(commitHash\)/);
  assert.match(html, /if \(compareSelection\) \{\s*contextMenu\.innerHTML = ''\s*\+\s*'<button class="context-menu-item" type="button" data-menu-action="compareCommits">Compare<\/button>'\s*\+\s*'<button class="context-menu-item" type="button" data-menu-action="cherryPickCommits">Cherry Pick<\/button>'/s);
  assert.match(html, /if \(compareSelection\) \{[\s\S]*?return;\s*\}\s*if \(isMultiSelectedContext\(commitHash\)\) \{\s*contextMenu\.innerHTML = '<button class="context-menu-item" type="button" data-menu-action="cherryPickCommits">Cherry Pick<\/button>';/s);
  assert.doesNotMatch(html, /if \(isMultiSelectedContext\(commitHash\)\) \{[\s\S]*?copyCommitHash[\s\S]*?showContextMenuAt\(clientX, clientY\);\s*return;/s);
  assert.doesNotMatch(html, /canCompareWithWorktree/);
  assert.doesNotMatch(html, /function isSingleSelectedCommit\(commitHash\)/);
  assert.match(html, /data-menu-action="openFile">Compare<\/button>/);
  assert.match(html, /Compare with Worktree/);
  assert.match(html, /data-menu-action="revertFileToCommit">Revert to this<\/button>/);
  assert.match(html, /Copy to Clipboard/);
  assert.match(html, /context-menu-group/);
  assert.match(html, /vscode\.postMessage\(\{ type: 'ready' \}\);/);
  assert.match(html, /type: 'toggleCommit', commitHash/);
  assert.match(html, /data-menu-action="compareCommits"/);
  assert.match(html, /type: 'compareCommits'/);
  assert.match(html, /type: 'compareCommitWithWorktree'/);
  assert.match(html, /type: 'cherryPickCommits', commitHashes: state\.commitHashes \|\| \[state\.commitHash\]/);
  assert.match(html, /type: 'checkoutCommit', commitHash: state\.commitHash/);
  assert.match(html, /type: 'createTagFromCommit', commitHash: state\.commitHash/);
  assert.match(html, /type: 'resetToCommit'/);
  assert.match(html, /baseCommitHash: state\.baseCommitHash/);
  assert.match(html, /compareCommitHash: state\.compareCommitHash/);
  assert.match(html, /data-menu-action="openFile"/);
  assert.match(html, /data-menu-action="compareWithWorktree"/);
  assert.match(html, /data-menu-action="revertFileToCommit"/);
  assert.match(html, /type: action,\s*commitHash: state\.commitHash,\s*changeId: state\.changeId/s);
  assert.match(html, /type: 'openCommitDetails', commitHash: state\.commitHash/);
  assert.doesNotMatch(html, /id="loadMoreButton"/);
});
